import type { DevelopersContent } from '../types';
import { LINKS, SITE } from '../../config';

/*
  The engine, for people who want to build on it rather than type with it.

  Every fact here is checkable against obadh_engine: the version, the feature
  names, the API names and the example all come out of the crate and its
  README. Nothing on this page describes something that does not exist, and the
  one thing that has not been built says so in its own heading.
*/
export const developers: DevelopersContent = {
  meta: {
    title: 'Obadh for developers: the Bangla engine as a library',
    description:
      'obadh_engine is a deterministic Roman to Bangla transliteration engine in Rust, MIT licensed, with a stable C ABI and WebAssembly bindings.',
    ogTitle: 'Build on Obadh',
    ogDescription:
      'The same Rust engine the keyboard runs, as a crate you can depend on. Deterministic, dictionary-free, MIT licensed.',
  },

  eyebrow: 'Developers',
  heading: 'The engine is a library first',
  standfirst:
    'Everything the keyboard does, your program can do. One Rust crate, no word list inside it, and the same output on every platform.',

  rust: {
    heading: 'The Rust crate',
    lede: 'Deterministic Roman to Bangla transliteration, plus the layers above it: tokenizing, autocorrect and next-word suggestion. The default feature set is empty, so a native dependant pays for none of the browser or CLI tooling.',
    facts: [
      { term: 'Crate', value: `obadh_engine ${SITE.versions.engine}` },
      { term: 'License', value: 'MIT' },
      { term: 'Size', value: 'About 390 KB compiled to WebAssembly' },
      { term: 'Data', value: 'No word list and no data files in the core' },
    ],
    blocks: [
      {
        label: 'Cargo.toml',
        lang: 'toml',
        code: `[dependencies]\nobadh_engine = "${SITE.versions.engine}"`,
      },
      {
        label: 'Transliterating',
        lang: 'rust',
        code: `use obadh_engine::ObadhEngine;\n\nlet engine = ObadhEngine::new();\nlet bangla = engine.transliterate("aji e probhate robir kor");\n\nassert_eq!(bangla, "আজি এ প্রভাতে রবির কর");`,
      },
      {
        label: 'Reusing a buffer, for an editor',
        lang: 'rust',
        code: `use obadh_engine::{ObadhEngine, PhoneticUnit};\n\nlet engine = ObadhEngine::new();\nlet mut units: Vec<PhoneticUnit> = Vec::new();\n\nengine.tokenize_phonetic_into("rrkSh", &mut units);`,
      },
    ],
    actions: [
      { label: 'Documentation on docs.rs', href: 'https://docs.rs/obadh_engine' },
      { label: 'crates.io', href: LINKS.crate },
    ],
  },

  bindings: {
    heading: 'From other languages',
    lede: 'Two optional features carry the engine out of Rust. Both are built and shipping: the iOS and macOS apps go through the C ABI, and the typing box on this site goes through the WebAssembly build.',
    rows: [
      {
        name: 'Native code',
        feature: 'cabi',
        body: 'A stable, versioned C ABI. UTF-8 buffers in, packed records out, no objects and no callbacks. This is how both Apple apps reach the engine.',
      },
      {
        name: 'The browser',
        feature: 'wasm',
        body: 'wasm-bindgen bindings, exposing <code>ObadhaWasm</code> with <code>transliterate</code> and the autosuggest session methods. This is what runs the box on the writing guide.',
      },
      {
        name: 'A terminal',
        feature: 'cli',
        body: 'The <code>obadh</code> binary. Every Bangla string on this site was generated by piping through it, which is why the site cannot disagree with the keyboard.',
      },
    ],
  },

  javascript: {
    heading: 'A JavaScript package, planned',
    state: 'Nobody has started this',
    lede: 'There is no npm package today, no repository and no date.',
    body: [
      'The hard part already exists. The <code>wasm</code> feature compiles the engine to WebAssembly and exposes it to JavaScript, and this site has been running that build in production since it launched.',
      'What is missing is the layer on top: a published package that wraps those bindings, loads the WebAssembly without ceremony, and binds to an ordinary text field so a web app gets Bangla input in a few lines instead of a few hundred. That is a real project and a well-scoped one, and it is open.',
    ],
    action: { label: 'Say you are taking it on', href: LINKS.github.engine + '/issues' },
  },

  repos: {
    heading: 'The repositories',
    rows: [
      {
        repo: 'engine',
        name: 'obadh_engine',
        body: 'The Rust engine, the C ABI, the WebAssembly build and the command-line tool.',
      },
      { repo: 'ios', name: 'obadh-ios', body: 'The iPhone and iPad keyboard, in Swift.' },
      { repo: 'macos', name: 'obadh-macos', body: 'The Mac input method, through InputMethodKit.' },
    ],
  },
};
