#!/usr/bin/env node
// Pulls the woff2 subsets Google Fonts serves for the families we use and writes
// them into public/fonts/ with a local @font-face sheet. Run it once; the output
// is committed so a build never touches the network.
//
//   node scripts/fetch-fonts.mjs

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = resolve(ROOT, 'public/fonts');

// A Chrome UA is what makes the API answer with woff2 + variable axes.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

const FAMILIES = [
  // Latin. Variable weight, used for everything in the English UI.
  { query: 'Schibsted+Grotesk:ital,wght@0,400..900;1,400..700', slug: 'schibsted-grotesk' },
  // Bangla. Anek is a contemporary Bangla design with a real text weight range.
  { query: 'Anek+Bangla:wdth,wght@100,100..800', slug: 'anek-bangla' },
  // Bangla text serif, for verse and long quotations.
  { query: 'Tiro+Bangla:ital@0;1', slug: 'tiro-bangla' },
  // The Roman side of every input example.
  { query: 'IBM+Plex+Mono:ital,wght@0,400;0,500;1,400', slug: 'ibm-plex-mono' },
];

const seen = new Map();

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return res.text();
}

async function download(url, filename) {
  if (seen.has(url)) return seen.get(url);
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} for ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  await writeFile(resolve(OUT_DIR, filename), buf);
  seen.set(url, filename);
  console.log(`  ${filename}  ${(buf.length / 1024).toFixed(1)} KB`);
  return filename;
}

await mkdir(OUT_DIR, { recursive: true });

const sheets = [];

for (const family of FAMILIES) {
  console.log(`\n${family.slug}`);
  const css = await fetchText(
    `https://fonts.googleapis.com/css2?family=${family.query}&display=swap`,
  );

  let index = 0;
  const rewritten = [];
  // Google emits one @font-face per unicode-range subset. Keep that split: it is
  // why a Latin-only page never downloads the Bengali glyph blocks.
  for (const block of css.split('@font-face').slice(1)) {
    const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    if (!url) continue;
    const filename = await download(url, `${family.slug}-${index++}.woff2`);
    rewritten.push(`@font-face${block.replace(url, `/fonts/${filename}`)}`.trim());
  }
  sheets.push(rewritten.join('\n'));
}

const header = `/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand.
   Families: ${FAMILIES.map((f) => f.query.split(':')[0].replaceAll('+', ' ')).join(', ')}
   Licensed under the SIL Open Font License 1.1. */\n\n`;

await writeFile(resolve(OUT_DIR, 'fonts.css'), header + sheets.join('\n\n') + '\n');
console.log('\nWrote public/fonts/fonts.css');
